### ISSUE TITLE
Laundry machine state toggle

### ISSUE THREAD

**Issue by abjeroen** [fyodorvi/homebridge-tuya-laundry-notify#1]
Great plugin! Is it possible to add a washingmachine state to homekit that enables when it notices the washing machine being on and disables when it's done?

**Comment by abjeroen** [comment]
maybe in combination with dummy switches? https://www.npmjs.com/package/homebridge-dummy

**Comment by fyodorvi** [comment]
@abjeroen makes sense

**Comment by fyodorvi** [comment]
@abjeroen less than a year later... this is done
